irqsteer: address the compile failure when CONFIG_PM_SLEEP is undefined
This compile problem surfaced during a configuration without the
PM_SLEEP being set.

 drivers/irqchip/irq-imx-irqsteer.c: In function 'imx_irqsteer_chans_enable':
 drivers/irqchip/irq-imx-irqsteer.c:203:27: error: 'irqsteer_data' undeclared
     (first use in this function)
   203 |  ret = clk_prepare_enable(irqsteer_data->ipg_clk);
       |                           ^~~~~~~~~~~~~
 drivers/irqchip/irq-imx-irqsteer.c:203:27: note: each undeclared identifier
     is reported only once for each function it appears in
 In file included from ./include/linux/device.h:23,
                  from ./include/linux/of_platform.h:9,
                  from drivers/irqchip/irq-imx-irqsteer.c:15:
 drivers/irqchip/irq-imx-irqsteer.c: At top level:
 drivers/irqchip/irq-imx-irqsteer.c:398:21: error:
     'imx_irqsteer_runtime_suspend' undeclared here (not in a function);
     did you mean 'pm_generic_runtime_suspend'?
   398 |  SET_RUNTIME_PM_OPS(imx_irqsteer_runtime_suspend,
       |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ./include/linux/pm.h:342:21: note: in definition of macro 'SET_RUNTIME_PM_OPS'
   342 |  .runtime_suspend = suspend_fn, \
       |                     ^~~~~~~~~~
 drivers/irqchip/irq-imx-irqsteer.c:399:7: error:
     'imx_irqsteer_runtime_resume' undeclared here (not in a function)
   399 |       imx_irqsteer_runtime_resume, NULL)
       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
 ./include/linux/pm.h:343:20: note: in definition of macro 'SET_RUNTIME_PM_OPS'
   343 |  .runtime_resume = resume_fn, \
       |                    ^~~~~~~~~
 make[5]: *** [scripts/Makefile.build:266: drivers/irqchip/irq-imx-irqsteer.o]

Signed-off-by: Charles Hardin <charles.hardin@chargepoint.com>