drm/mxsfb: rename driver to mxsfb-drm
There are two drivers for the LCDIF/MXSFB peripheral. If the DRM
and fbdev are compiled in, the registration of the second driver
fails:
  mxs-dma 33000000.dma-apbh: initialized
  mxsfb 30730000.lcdif: 30730000.lcdif supply lcd not found, using dummy regulator
  mxsfb 30730000.lcdif: initialized
  Error: Driver 'mxsfb' is already registered, aborting...

Avoid driver name conflict with MXS fbdev driver by renaming the
more recently added DRM driver.

Signed-off-by: Stefan Agner <stefan@agner.ch>